controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

delete_user:
    path: /delete-user/{id}
    controller: App\Controller\YourController::deleteAction
